# Bot configurations
api-key: "OP185aWACBkcqpPVMVMsyUfHZuMdWCOmVAmH5fOVTsYhCKC9Y5qCmglTFJcmPkPE"
secret-key: "qeSevC9FZ9aCTNVUVnMAEUwLcFyTXvaEoZM6yt0rmo2iDC3IvpaTKu1YL585PR0p"
symbol: "BTCBUSD"
port: "8080"
