# Bot configurations

# binance api key
api-key: ""
# binance secret key
secret-key: ""
# use testnet or not
use-test-net: false
# trading pair
symbol: "BTCBUSD"
# port for bot
port: "8080"

# minimal trade amount
trade-amount: 300.0
# take profit in percent
profit-in-percent: 0.01
stop-sum-of-open-orders-for-last-day: 2000
daily-ratio-for-stop-price: 0.50
weekly-ratio-for-stop-price: 0.50
time-until-last-trade-price-will-reset: 7200