# Bot configurations
api-key: "iA6CnpnsLfL5YlsRFl4htn5yc1qc9tFs4rJppVOmqIXpRsv90V03ilLzbImfH4kY"
secret-key: "B9l5KX5xshGoR8O298LBfJPsNotJw7AylvMjiLn4DdOhwKu0aUudTN1RZjPpAVTT"
symbol: "BTCBUSD"
port: "8080"
